# @package _global_

type: sfm
work_dir: ${hydra:runtime.cwd}
redo: False

scan_data_dir: ${work_dir}/data/onepose_datasets/test_data

dataset:
    max_num_kp3d: 2500
    max_num_kp2d: 1000
  
    data_dir:
        - ${scan_data_dir}/0408-colorbox-box colorbox-1 
        - ${scan_data_dir}/0409-aptamil-box aptamil-1
        - ${scan_data_dir}/0419-cookies2-others cookies2-1
        - ${scan_data_dir}/0422-qvduoduo-box qvduoduo-1
        - ${scan_data_dir}/0423-oreo-box oreo-1
        - ${scan_data_dir}/0424-chocbox-box chocbox-1
        - ${scan_data_dir}/0447-nabati-box nabati-1
        - ${scan_data_dir}/0450-hlychocpie-box hlychocpie-1
        - ${scan_data_dir}/0452-hlymatchapie-box hlymatchapie-1
        - ${scan_data_dir}/0455-strawberryoreo-box strawberryoreo-1
        - ${scan_data_dir}/0456-chocoreo-box chocoreo-1
        - ${scan_data_dir}/0458-hetaocakes-box hetaocakes-1
        - ${scan_data_dir}/0459-jzhg-box jzhg-1
        - ${scan_data_dir}/0466-mfmilkcake-box mfmilkcake-1
        - ${scan_data_dir}/0468-minipuff-box minipuff-1
        - ${scan_data_dir}/0469-diycookies-box diycookies-1
        - ${scan_data_dir}/0470-eggrolls-box eggrolls-1
        - ${scan_data_dir}/0471-hlyormosiapie-box hlyormosiapie-1
        - ${scan_data_dir}/0472-chocoreo-bottle chocoreo-1
        - ${scan_data_dir}/0473-twgrassjelly1-box twgrassjelly1-1
  
    outputs_dir: ${work_dir}/data/sfm_model/{}

network:
    detection: superpoint
    detection_model_path: ${work_dir}/data/models/extractors/SuperPoint/superpoint_v1.pth

    matching: superglue
    matching_model_path: ${work_dir}/data/models/matchers/SuperGlue/superglue_outdoor.pth

sfm:
    down_ratio: 5
    covis_num: 10
    rotation_thresh: 50

disable_lightning_logs: True
    
